version: '3.8'
services:
  kunsolved-backend:
    build:
      dockerfile: ./main.Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
  kunsolved-db:
    image: 'mysql'
    volumes:
      - mysql-volume:/var/lib/mysql
    env_file:
      - ./mysql.env
  scheduler:
    build:
      dockerfile: ./scheduler.Dockerfile

volumes:
  mysql-volume:
