version: '3.8'
services:
  kunsolved_backend:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
  kunsolved_db:
    image: 'mysql'
    volumes:
      - mysql-volume:/var/lib/mysql
    env_file:
      - ./mysql.env

volumes:
  mysql-volume:
